steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_ARTIFACT_NAME}:${_VERSION}", "--build-arg=JAR_FILE=target/${_ARTIFACT_NAME}-${_VERSION}-SNAPSHOT.jar", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_ARTIFACT_NAME}:${_VERSION}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_ARTIFACT_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_ARTIFACT_NAME}:${_VERSION}', '--region', '${_REGION}', '--platform', 'managed', '--allow-unauthenticated']
images: ["gcr.io/$PROJECT_ID/${_ARTIFACT_NAME}:${_VERSION}"]
substitutions:
  _VERSION: 0.0.1
  _ARTIFACT_NAME: springongcp-cloudrun
  _REGION: europe-north1
